# TODO: prejmenovat na positions held nebo tak neco
SELECT ?person ?personLabel ?position ?positionLabel ?election ?electionLabel ?startedLabel ?endedLabel
       ?district ?districtLabel ?term ?termLabel ?replaces ?replacesLabel ?replacedBy ?replacedByLabel
WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "cs". }
  ?person p:P6828 ?parliamentId.
  ?person p:P39 ?statement. ?statement ps:P39 ?position.
  OPTIONAL{?statement pq:P2715 ?election.} # a vytahnem si obdobi
  OPTIONAL{?statement pq:P580 ?started.}
  OPTIONAL{?statement pq:P582 ?ended.}
  OPTIONAL{?statement pq:P768 ?district.}
  OPTIONAL{?statement pq:P2937 ?term.}
  OPTIONAL{?statement pq:P1365 ?replaces.}
  OPTIONAL{?statement pq:P1366 ?replacedBy.}
}
LIMIT 100000
